version: "3.8"
services:
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    depends_on:
      - user-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
      - POSTGRES_HOST=user-db

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  booking-service:
    build: ./booking-service
    ports:
      - "8081:8081"
    depends_on:
      - booking-db

  booking-db:
    image: postgres:16
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5433:5432"
