services:
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    depends_on:
      - user-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
      - POSTGRES_HOST=user-db

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  booking-service:
    build: ./booking-service
    ports:
      - "8081:8081"
    depends_on:
      - booking-db

  booking-db:
    image: postgres:16
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5433:5432"
  
  availability-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - availability_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=availabilitydb

  availability-service:
    build: ./availability-service
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=mongodb://availability-db:27017/availabilitydb
    depends_on:
      - availability-db

volumes:
  availability_data: